version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
      args:
        - "PROJECT_NAME=${PROJECT_NAME}"
        - "PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}"
        - "APACHE_DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}"
    container_name: "${PROJECT_NAME}-app"
    labels:
      - "traefik.backend=${PROJECT_NAME}-app"
      - traefik.enable=true
      - traefik.docker.network=web
      - "traefik.frontend.rule=Host:${PROJECT_NAME}.${DOMAIN_SUFFIX}"
      - traefik.port=80
      - traefik.protocol=http
    working_dir: "/var/www/project"
    environment:
      - "SSH_AUTH_SOCK:/tmp/agent.sock"
    env_file:
      - ./.env
    volumes:
      - "$SYNC_PATH/:/var/www/project:cached"
      - "$DUMP_PATH/:/dump"
      - "/tmp/agent.sock:/tmp/agent.sock"
    networks:
      - web
  maildev:
      image: djfarrelly/maildev:latest
      container_name: "${PROJECT_NAME}-maildev"
      labels:
        - "traefik.backend=${PROJECT_NAME}-mail"
        - traefik.enable=true
        - traefik.docker.network=web
        - "traefik.frontend.rule=Host:${PROJECT_NAME}.mail.${DOMAIN_SUFFIX}"
        - traefik.port=80
        - traefik.protocol=http
      networks:
        - web
  db:
    image: mariadb:latest
    volumes:
      - ./db/dump:/var/lib/mysql:delegated
    container_name: "${PROJECT_NAME}-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - web
    ports:
      - '3306:3306'
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}-phpmyadmin"
    labels:
      - "traefik.backend=${PROJECT_NAME}-phpmyadmin"
      - traefik.enable=true
      - traefik.docker.network=web
      - "traefik.frontend.rule=Host:${PROJECT_NAME}.phpmyadmin.${DOMAIN_SUFFIX}"
      - traefik.port=80
      - traefik.protocol=http
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: testing
    networks:
      - web
networks:
  web:
    external: true
